### ISSUE TITLE
Installing pip packages as root (sudo) is against best practices

### ISSUE THREAD

**Issue by cdsimpkins** [anthonyw12123/4chanwebscraper#11]
Your project, so it's up to you, but I suggest you either use Python virtual environments or a fresh, non-default installation of python.

Virtual Environments are best in my opinion, because it allows you to manage dependencies for a project with no dependence on any packages installed system-wide.

**Comment by anthonyw12123** [comment]
[This](http://stackoverflow.com/a/6944649) could be a route to implementing this.

**Comment by cdsimpkins** [comment]
Virtual environments are pretty straight-forward.  There's really no need for something to wrap around it.  The real work will be in fixing your specific local environment to support it.

**Comment by anthonyw12123** [comment]
Created a new brach with a requirements.txt file with the necessary packages so far, and a venv folder. Remaining to do is determine whether the venv folder is necessary, or if the requirements file needs to mention `virtualenv`.

**Comment by cdsimpkins** [comment]
i just submitted #17, in which i answered that question. sorry i didn't check before posting.  for the second question, the answer is no.  you don't reference the venv from the requirements file, as the requirements file is just a list of dependencies necessary for the project.  it's meant so new developers have a succinct list of packages to have before development starts.  

`pip freeze > requirements.txt` creates a file, and `pip install -r requirements.txt` installs all the packages at the listed versions from the requirements file.

**Comment by anthonyw12123** [comment]
The requirements file is in 1.1; so unless something is amiss, I would think it ok to close the ticket.

**Comment by cdsimpkins** [comment]
you can close it if you want, but you should update the readme first to avoid confusion.

**Comment by cdsimpkins** [comment]
fixed in f7810e8
