### ISSUE TITLE
Use argparse library for parsing command-line arguments

### ISSUE THREAD

**Issue by cdsimpkins** [anthonyw12123/4chanwebscraper#12]
argparse is a standard python library included at least since 2.7.  It allows for the creation of self-documenting arguments and usage hints, as well as argument validation without you having to write lots of boiler-plate code.

[Documentation](https://docs.python.org/3/library/argparse.html)

**Comment by cdsimpkins** [comment]
this is related to #1  and #2

**Comment by anthonyw12123** [comment]
Implemented. This will be merged into the 1.1 branch for testing here in a bit.
