### ISSUE TITLE
Python Virtual Environment should not be in the repository

### ISSUE THREAD

**Issue by cdsimpkins** [anthonyw12123/4chanwebscraper#17]
the virtual environment contains compiled python binaries and libraries that are unique to the user's machine.  this may cause problems when another user takes up the build.  remove it from the repo and add it to the .gitignore

**Comment by anthonyw12123** [comment]
venv is already in the gitignore file. I'll research why it isn't excluding it.

**Comment by anthonyw12123** [comment]
Fix is in 1.1

**Comment by cdsimpkins** [comment]
you probably came across this, but in answer to "why is it in there" .gitignore only works on files that are "new" to the repo.  if you tracked venv before adding it to .gitignore, it doesn't remove it from the repo.
