### ISSUE TITLE
Install prereqs if needed for operation

### ISSUE THREAD

**Issue by anthonyw12123** [anthonyw12123/4chanwebscraper#5]
It would be cool if the scraper asked the user to install the prereqs for the utility, if they were needed.

**Comment by cdsimpkins** [comment]
suggestion: 
`pip freeze > requirements.txt`
then add that file to the repository.  new users could then run 
`pip install -r requirements.txt` to get up to date.

**Comment by anthonyw12123** [comment]
This is settled in the requirements file. Closing this would involve placing a file with instructions for use.

**Comment by anthonyw12123** [comment]
This file has been created in 1.1
